### ISSUE TITLE
Packing into single executable (for easy distribution)

### ISSUE THREAD

**Issue by Frityet** [luawax/wit#3]
How would I use this framework to easily pack all my code into a single executable that has no dependencies?

**Comment by arkt8** [comment]
Basically, Lupe is intended to "isolate" the project from the environment in a way you can put your Lua modules, your Lua scripts (executables like shellscripts) and your dependencies (from Luarocks or not) under the same directory structure, pack it as .tgz, .zip, .deb or even cloning for git on the target and it is ready to be used. You can have in the same machine multiple equal projects using Lupe folder running with different datasets and dependencies if you want to.

Also linking the Lua script under the project `./bin/XXXX.lua` to the `$PATH` the shebang solve it (via POSIX `realpath`) to the right project folder and Lua version.

So you could, for example, create a .tgz, .zip or .deb package and distribute it to any POSIX compliant system since the target machine have a Lupe installed.

But, what is difference with or not Lupe?

Without Lupe you would need to install every dependency with Luarocks,
have 3rd part code not distributed with Luarocks messed with your own project code and think about a way to run in different Linux/Unix flavors shebanging your code for the right Lua binary (lua5.1 vs lua51). So Lupe provides, by now, a simple abstraction that try to simplify project creation and sufficient compatibility to work with Lua 5.1 to 5.4.

That said, I see no much way to use the Lupe as is now in a project like yours (by the way we had talked before), as it is intended from the start to be used as unpacked directories (but still isolated) with plain Lua scripts as entry points, not precompiled ones.

The best I can guess in your case... is that if you understood the "grok" of the Lupe, is to take some ideas from it as the start point for your project. The lupe.c is very very minimal and mostly deal with string parsing of project conf and environment scanning for the Lua binary. 

If you intend to make a portable way... perhaps you should think in a way to recopile the Lua binary with the folder zipped and loading a kind of main.lua from the zipped and resolving the path to this zip. I see no other way to create a standalone executable with all the Lua scripts.

Also remember that from the C you can always load a `.lua` file and run it via the `lua_load` Lua C Api function.

**Comment by Frityet** [comment]
👍 thanks!
